import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import styled from 'styled-components';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>eMetal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://emetalexchange.firebaseapp.com/">eMetal</a>
        </h1>
      </main>
      <Test>test</Test>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          eMetal
        </a>
      </footer>
    </div>
  );
};

const Test = styled.div`
  width: 30px;
  background: #0070f3;
  border: 1px solid red;
`;

export default Home;
